spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userLogin
    username: root
    password: swnemo0501
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
